# ---------- ENVY / Streamlit Secrets ----------
# 이 파일을 프로젝트 루트의 .streamlit/secrets.toml 로 저장하세요.
# 값은 수정 즉시 앱 재시작 없이도 반영될 수 있습니다(런타임/배포 환경에 따라 다름).

# Rakuten API
RAKUTEN_APP_ID       = "1043271015809337425"
RAKUTEN_AFFILIATE_ID = "4c723498.cbfeca46.4c723499.1deb6f77"

# Naver Developers (네이버 개발자 콘솔의 Client ID / Secret)
# * 이 값은 로그인/일반 Open API 용이며, '검색광고 API'와는 별개입니다.
NAVER_CLIENT_ID     = "h4mklM2hNLct04BD7sC0"
NAVER_CLIENT_SECRET = "ltoxUNyKxi"

# Naver Ads / 검색광고 API (키워드 도구)
# 아래 두 개는 business.ad.naver.com → API 사용관리 화면의
#  - 엑세스 라이선스(= NAVER_API_KEY)
#  - 비밀키(= NAVER_SECRET_KEY)
# 에서 복사해 붙여넣으세요.
NAVER_API_KEY     = "0100000000785cf1d8f039b13a5d3c3d1262b84e9ad4a046637e8887bbd003051b0d2a5cdf"
NAVER_SECRET_KEY  = "AQAAAAB4XPHY8DmxOl08PRJiuE6ao1LN3lh0kF9rOJ4m5b8O5g=="
NAVER_CUSTOMER_ID = "629744"

# (선택) 프록시들 – 다른 값으로 바꾸고 싶으면 수정
NAVER_PROXY       = "https://envy-proxy.taesig0302.workers.dev"
ELEVENST_PROXY    = "https://worker-11stjs.taesig0302.workers.dev"
ITEMSCOUT_PROXY   = "https://worker-itemscoutjs.taesig0302.workers.dev"
SELLERLIFE_PROXY  = "https://worker-sellerlifejs.taesig0302.workers.dev"
